-- ============================================
-- Equipment Borrowing and Return Monitoring System
-- Run this whole file inside Supabase SQL Editor
-- ============================================

-- 1. EQUIPMENT TABLE
CREATE TABLE equipment (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  equipment_name TEXT NOT NULL,
  category TEXT NOT NULL,
  asset_code TEXT UNIQUE NOT NULL,
  condition TEXT DEFAULT 'Good',GRANT USAGE ON SCHEMA public TO authenticated, anon;

GRANT ALL ON ALL TABLES IN SCHEMA public TO authenticated;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO anon;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;
  availability TEXT DEFAULT 'Available',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. BORROW TRANSACTIONS TABLE
CREATE TABLE borrow_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  equipment_id BIGINT REFERENCES equipment(id),
  borrower_name TEXT NOT NULL,
  borrower_type TEXT NOT NULL,
  department TEXT NOT NULL,
  date_borrowed DATE DEFAULT CURRENT_DATE,
  due_date DATE NOT NULL,
  date_returned DATE,
  status TEXT DEFAULT 'Borrowed',
  user_id UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. ENABLE ROW LEVEL SECURITY
ALTER TABLE equipment ENABLE ROW LEVEL SECURITY;
ALTER TABLE borrow_transactions ENABLE ROW LEVEL SECURITY;

-- 4. POLICIES: only logged-in (authenticated) users can read/write
-- Equipment policies
CREATE POLICY "Authenticated users can view equipment"
  ON equipment FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Authenticated users can insert equipment"
  ON equipment FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Authenticated users can update equipment"
  ON equipment FOR UPDATE
  TO authenticated
  USING (true);

CREATE POLICY "Authenticated users can delete equipment"
  ON equipment FOR DELETE
  TO authenticated
  USING (true);

-- Borrow transactions policies
CREATE POLICY "Authenticated users can view transactions"
  ON borrow_transactions FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Authenticated users can insert transactions"
  ON borrow_transactions FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Authenticated users can update transactions"
  ON borrow_transactions FOR UPDATE
  TO authenticated
  USING (true);

-- 5. SAMPLE DATA (optional, para naa'y makita dayon)
INSERT INTO equipment (equipment_name, category, asset_code, condition, availability) VALUES
('Epson Projector', 'Projector', 'PROJ-001', 'Good', 'Available'),
('Acer Laptop', 'Laptop', 'LAP-002', 'Good', 'Available'),
('Canon Camera', 'Camera', 'CAM-001', 'Fair', 'Available'),
('TP-Link Router', 'Router', 'RTR-001', 'Good', 'Available');
